### ISSUE TITLE
BETA_03_00_08_B4 - network inclusion issues

### ISSUE THREAD

**Issue by gorbunovav** [Z-Wave-Me/Z-Uno-G2-Core#1]
With the latest beta (BETA_03_00_08_B4) `zunoNID()` reports 165 right after the boot-loader update and sketch upload / factory reset (not sure that reset works).

**Comment by p0lyg0n1** [comment]
We have already faced this problem. This happens when transferring from the previous SDK to the newest one when Z-Uno was included in the network.
You need to clean system memory to avoid this.  The easiest way is to use the "Reset Locally" procedure using the button. Hold the button until the red LED starts flashing, release the button. Press the button three times, and after that the device memory will be reset.
Another approach is to use zme_make (it ships with toolchain, you can find it inside ZUno2 folder of ArduinoIDE) utility. This utility will give you more control and feedback.
0. Run terminal utility (cmd for Windows) inside zme_make directory.
1. For Windows:  **zme_make.exe boardInfo -d <yourZUNOCOM>**  
    For Linux/OSx:   **zme_make boardInfo -d <yourZUNOTTY>** 
2. You will see your board Information. The most significant for your case is "NETWORK" section. Remember your current HomeID/NodeID
3. For Windows:  **zme_make.exe eraseNVM -d <yourZUNOCOM>**  
    For Linux/OSx:   **zme_make eraseNVM -d <yourZUNOTTY>** 
4. Once more. For Windows:  **zme_make.exe boardInfo -d <yourZUNOCOM>**  
    For Linux/OSx:   **zme_make boardInfo -d <yourZUNOTTY>**
 5. After step 4 your NodeID has to be 0, your HomeId has to be another.
 6. If you see the same NodeID/HomeId (as they were before at the step 2 ) please write me .
